---
sidebar: sidebar 
permalink: concept-before-you-begin-to-deploy-gfc.html 
keywords: global file cache, core, edge, management server 
summary: Hay muchos requisitos que debes tener en cuenta antes de empezar a implementar el almacenamiento en caché perimetral de BlueXP en la nube y en tus oficinas remotas. 
---
= Antes de empezar a implementar el almacenamiento en caché perimetral de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay muchos requisitos que debes tener en cuenta antes de empezar a implementar el almacenamiento en caché perimetral de BlueXP en la nube y en tus oficinas remotas.



== Consideraciones de diseño del núcleo sobre el almacenamiento en caché perimetral de BlueXP

En función de tus requisitos, puede que tengas que implementar una o varias instancias principales de almacenamiento en caché en el edge de BlueXP para crear la estructura de almacenamiento en caché en el edge de BlueXP. La instancia de Core está diseñada para dirigir el flujo de tráfico entre las instancias distribuidas de almacenamiento en caché perimetral de BlueXP y los recursos del servidor de archivos del centro de datos, por ejemplo, recursos compartidos de archivos, carpetas y archivos.

Cuando diseñas la puesta en marcha de almacenamiento en caché perimetral de BlueXP, debes determinar qué es adecuado para tu entorno en cuanto a escala, disponibilidad de recursos y redundancia. El almacenamiento en caché perimetral Core de BlueXP se puede poner en marcha de las siguientes maneras:

* Instancia autónoma
* Diseño distribuido de carga (espera en frío)


Consulte <<Directrices de tamaño>> Para comprender el número máximo de instancias de Edge y el total de usuarios que cada configuración admite:

Consulte a su ingeniero de soluciones de NetApp para analizar las mejores opciones para la implementación de su empresa.



== Directrices de tamaño

Hay algunas pautas de tamaño que debe tener en cuenta a la hora de configurar el sistema inicial. Debe volver a revisar estas relaciones una vez acumulado algún historial de uso para asegurarse de que está utilizando el sistema de forma óptima. Entre ellos se incluyen:

* Relación de aristas/núcleo
* Ratio de usuarios distribuidos/borde
* Ratio de usuarios distribuidos/núcleo




=== Número de instancias de Edge por instancia de Core

Nuestras directrices recomiendan hasta 10 instancias de Edge por instancia de Core en almacenamiento en caché perimetral de BlueXP, con un máximo de 20 aristas por instancia de Core en caché perimetral de BlueXP. Depende en gran medida del tipo y el tamaño medio de los archivos de la carga de trabajo más común. En algunos casos, con cargas de trabajo más comunes puede añadir más instancias de Edge por Core, pero en estos casos debe ponerse en contacto con su representante de cuenta para determinar cómo dimensionar correctamente el número de instancias de Edge y Core, en función de los tipos y tamaños de los conjuntos de archivos.


NOTE: Puedes aprovechar varias instancias del almacenamiento en caché perimetral de BlueXP al mismo tiempo para escalar horizontalmente tu infraestructura en función de los requisitos.



=== Número de usuarios simultáneos por instancia de Edge

El edge caching Edge de BlueXP se encarga del trabajo más pesado en términos de algoritmos de almacenamiento en caché y diferenciación a nivel de archivo. Una única instancia de Edge puede servir hasta 500 usuarios por instancia de Edge dedicada _physical_ y hasta 300 usuarios para implementaciones _virtual_ dedicadas. Depende en gran medida del tipo y el tamaño medio de los archivos de la carga de trabajo más común. Para tipos de archivos de colaboración de mayor tamaño, guía hacia el 50 % del número máximo de usuarios por almacenamiento en caché en el edge de BlueXP Edge límite inferior (en función de la puesta en marcha física o virtual). Para elementos de Office más comunes con un tamaño de archivo medio <1MB MB, guíe hacia el límite superior del 100% de usuarios por borde (dependiendo de la implementación física o virtual).


NOTE: El almacenamiento en caché perimetral de BlueXP detecta si se ejecuta en una instancia virtual o física y limitará el número de conexiones SMB al recurso compartido de archivos virtual local al máximo de 300 o 500 conexiones simultáneas.



=== Número de usuarios simultáneos por instancia de Core

La instancia principal de almacenamiento en caché perimetral de BlueXP es extremadamente escalable, con un recuento de usuarios simultáneos recomendado de 3.000 usuarios por núcleo. Depende en gran medida del tipo y el tamaño medio de los archivos de la carga de trabajo más común.

Consulte a su ingeniero de soluciones de NetApp para analizar las mejores opciones para la implementación de su empresa.



== Requisitos previos

Los requisitos previos descritos en esta sección son para los componentes instalados en la nube: El servidor de gestión de almacenamiento en caché perimetral de BlueXP y el núcleo de almacenamiento en caché perimetral de BlueXP.

Se describen los requisitos previos de BlueXP edge caching Edge link:download-gfc-resources.html#bluexp-edge caching-edge-requirements[aquí].



=== Plataforma de almacenamiento (volúmenes)

La plataforma de almacenamiento del entorno de administración, en este caso, la instancia de Cloud Volumes ONTAP implementada, debería presentar recursos compartidos de archivos SMB. Cualquier recurso compartido que se exponga a través del almacenamiento en caché perimetral de BlueXP debe permitir el control total del grupo «Todos» en el nivel de recurso compartido, al tiempo que restringe los permisos mediante permisos NTFS.

Si no ha configurado al menos un recurso compartido de archivos SMB en la instancia de Cloud Volumes ONTAP, debe tener lista la siguiente información para poder configurar esta información durante la instalación:

* Nombre de dominio de Active Directory, dirección IP del servidor de nombres y credenciales de administración de Active Directory.
* El nombre y el tamaño del volumen que se desea crear, el nombre del agregado en el que se creará el volumen y el nombre del recurso compartido.


Recomendamos que el volumen sea lo suficientemente grande como para alojar el conjunto de datos total para la aplicación junto con la capacidad de escalar en función de lo que crezca el conjunto de datos. Si tiene varios agregados en el entorno de trabajo, consulte https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-aggregates.html["Gestión de los agregados existentes"^] para determinar qué agregado tiene el espacio más disponible para el nuevo volumen.



=== Servidor de gestión de almacenamiento en caché perimetral de BlueXP

El servidor de administración de almacenamiento en caché perimetral de BlueXP requiere acceso externo a través de HTTPS (puerto TCP 443) para conectarse al servicio de suscripción del proveedor de cloud y acceder a estas direcciones URL:

* \https://gfcproxyforcm-prod.azurewebsites.net/
* \https://rest.zuora.com/v1/subscriptions/
* \https://rest.zuora.com/oauth/token
* \https://talonazuremicroservices.azurewebsites.net
* \https://talonlicensing.table.core.windows.net


Este puerto debe excluirse de todos los dispositivos de optimización WAN o las políticas de restricción del firewall para que el software de almacenamiento en caché perimetral de BlueXP funcione correctamente.

El servidor de gestión de almacenamiento en caché perimetral de BlueXP también requiere un nombre NetBIOS único (geográfico) para la instancia (como GFC-MS1).


NOTE: Un Management Server puede admitir múltiples instancias principales de almacenamiento en caché perimetral de BlueXP implementadas en diferentes entornos de trabajo. Cuando se implementa desde BlueXP, cada entorno de trabajo tiene su propio almacenamiento back-end independiente y no contendría los mismos datos.



=== Núcleo de almacenamiento en caché perimetral de BlueXP

El núcleo de almacenamiento en caché perimetral de BlueXP escucha en el intervalo de puertos TCP de 6618 a 6630. En función de su firewall o de la configuración del grupo de seguridad de red (NSG), es posible que tenga que permitir explícitamente el acceso a estos puertos mediante reglas de puerto entrantes. Además, estos puertos deben excluirse de cualquier dispositivo de optimización WAN o políticas de restricción del firewall para que el software de almacenamiento en caché perimetral de BlueXP funcione correctamente.

Los requisitos básicos de almacenamiento en caché perimetral de BlueXP son:

* Nombre NetBIOS exclusivo (geográfico) para la instancia (Como GFC-CORE1)
* Nombre de dominio de Active Directory
+
** Las instancias deben unirse al dominio de Active Directory.
** Las instancias deben gestionarse en una unidad organizativa específica (OU) del almacenamiento en caché perimetral de BlueXP y se deben excluir de los GPO de la empresa heredados.


* Cuenta de servicio. Los servicios del Core se ejecutan como una cuenta de usuario de dominio específica. Esta cuenta, también conocida como cuenta de servicio, debe tener los siguientes privilegios en cada uno de los servidores SMB que se asociarán con la instancia principal de almacenamiento en caché en el perímetro de BlueXP:
+
** La cuenta de servicio aprovisionada debe ser un usuario de dominio.
+
Dependiendo del nivel de restricciones y GPO del entorno de red, esta cuenta podría requerir privilegios de administrador de dominio.

** Debe tener privilegios de "Ejecutar como servicio".
** La contraseña se debe establecer en "no caducar nunca".
** La opción de cuenta "el usuario debe cambiar la contraseña en el siguiente inicio de sesión" debe ESTAR DESACTIVADA (sin marcar).
** Debe ser miembro del grupo operadores de copia de seguridad integrados del servidor de archivos de fondo (esto se habilita automáticamente cuando se implementa a través de BlueXP).






=== Servidor de gestión de licencias

* El servidor de gestión de licencias (LMS) de almacenamiento en caché perimetral de BlueXP debe configurarse en una edición Microsoft Windows Server 2016 Standard o Datacenter, o en una edición de Windows Server 2019 Standard o Datacenter, preferiblemente en la instancia de núcleo de almacenamiento en caché perimetral de BlueXP en el centro de datos o la nube.
* Si necesitas una instancia independiente de LMS en almacenamiento en caché en el edge de BlueXP, tienes que instalar el paquete de instalación del software de almacenamiento en caché en el edge de BlueXP en una instancia perfecta de Microsoft Windows Server.
* La instancia LMS debe poder conectarse al servicio de suscripción (Internet pública) mediante HTTPS (puerto TCP 443).
* Las instancias Core y Edge deben conectarse a la instancia LMS mediante HTTPS (puerto TCP 443).




=== Redes (acceso externo)

El LMS de almacenamiento en caché perimetral de BlueXP requiere acceso externo a través de HTTPS (puerto TCP 443) a las siguientes URL.

* Si utiliza licencias basadas en suscripción mediante GFC:
+
** \https://rest.zuora.com/v1/subscriptions/<subscription-no>
** \https://rest.zuora.com/oauth/token


* Si utiliza una licencia basada en NSS de NetApp:
+
** \https://login.netapp.com
** \https://login.netapp.com/ms_oauth/oauth2/endpoints
** \https://login.netapp.com/ms_oauth/oauth2/endpoints/oauthservice/tokens


* Si utiliza licencias basadas en productos heredados de NetApp:
+
** \https://talonazuremicroservices.azurewebsites.net
** \https://talonlicensing.table.core.windows.net






=== Redes

* Firewall: Se deben permitir los puertos TCP entre el almacenamiento en caché perimetral de BlueXP y las instancias de Edge.
* Puertos TCP de almacenamiento en caché perimetral de BlueXP: 443 (HTTPS), 6618-6630.
* Los dispositivos de optimización de redes (como Riverbed Steelhead) deben estar configurados para que pasen a través de los puertos específicos del almacenamiento en caché perimetral de BlueXP (TCP 6618-6630).

