---
sidebar: sidebar 
permalink: download-gfc-resources.html 
keywords: global file cache, edge 
summary: Hay muchos requisitos que debes tener en cuenta antes de empezar a instalar el software BlueXP edge caching Edge en tus oficinas remotas. 
---
= Antes de empezar a poner en marcha instancias de Edge sobre almacenamiento en caché perimetral de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay muchos requisitos que debes tener en cuenta antes de empezar a instalar el software BlueXP edge caching Edge en tus oficinas remotas.



== Descargue los recursos necesarios

Descargue las plantillas virtuales de almacenamiento en caché de BlueXP que planea utilizar en sus sucursales, el paquete de instalación de software y la documentación de referencia adicional:

* Plantilla virtual de Windows Server 2016:
+
https://repo.cloudsync.netapp.com/gfc/2k16-2_3_0-55.zip["Windows Server 2016 .OVA, incluido GFC de NetApp (VMware vSphere 6.5+)"^]
https://repo.cloudsync.netapp.com/gfc/2k16_GFC_2_3_0_55IMAGE.zip["Windows Server 2016 .VHDX, incluido NetApp GFC (Microsoft Hyper-v)"^]

* Plantilla virtual de Windows Server 2019:
+
https://repo.cloudsync.netapp.com/gfc/2k19-2_3_0-55.zip["Windows Server 2019 .OVA, incluido GFC de NetApp (VMware vSphere 6.5+)"^]
https://repo.cloudsync.netapp.com/gfc/2k19_GFC_2_3_0_55IMAGE.zip["Windows Server 2019 .VHDX, incluido NetApp GFC (Microsoft Hyper-v)"^]

* Software BlueXP Edge Caching Edge:
+
https://repo.cloudsync.netapp.com/gfc/GFC-2-3-0-55-Release.exe["Paquete de instalación de software GFC de NetApp (.EXE)"^]

* Paneles de control de caché de archivos global para Cloud Insights:
+
https://repo.cloudsync.netapp.com/gfc/ci-gfc-dashboards.zip["Paneles Cloud Insights GFC de NetApp (.ZIP)"]

* Documentación de Global File Cache:
+
https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Guía del usuario de NetApp Global File Cache (.PDF)"^]



link:task-deploy-gfc-edge-instances.html#update-bluexp-edge-caching-edge-software["Siga estos pasos"] Para actualizar el software BlueXP Edge de almacenamiento en caché perimetral.


NOTE: Al poner en marcha el almacenamiento en caché perimetral de BlueXP en Windows Server 2016, debería utilizar .NET Framework 4,8 y el marco de Windows WebView2.



== Diseñar y poner en marcha el almacenamiento en caché perimetral de BlueXP

En función de sus requisitos, es posible que necesite implementar una o varias instancias de Edge basadas en las sesiones de usuario simultáneas en una sucursal. La instancia de Edge presenta el recurso compartido de archivos virtuales a los usuarios finales dentro de la sucursal, que se amplía de forma transparente desde la instancia de Core asociada de almacenamiento en caché en edge de BlueXP. El almacenamiento en caché perimetral de BlueXP debería contener un `D:\` Volumen NTFS, que contiene los archivos almacenados en caché dentro de la sucursal.


NOTE: Para el almacenamiento en caché perimetral de BlueXP, es importante comprender el link:concept-before-you-begin-to-deploy-gfc.html#sizing-guidelines["directrices de tamaño"]. Esto te ayudará a realizar el diseño correcto para la puesta en marcha de almacenamiento en caché en el edge de BlueXP. También debe determinar qué es mejor para su entorno en términos de escalado, disponibilidad de recursos y redundancia.



=== Instancia de Edge en caché en edge de BlueXP

Al poner en marcha una instancia de almacenamiento en caché perimetral de BlueXP, necesitas aprovisionar una única máquina virtual, ya sea mediante la implementación de Windows Server 2016 2019 Standard o Datacenter Edition, o bien mediante el almacenamiento en caché perimetral `.OVA` o. `.VHD` Plantilla, que incluye el sistema operativo Windows Server elegido y el software de almacenamiento en caché perimetral de BlueXP.



==== Pasos rápidos

. Implementa la plantilla virtual de almacenamiento en caché perimetral de BlueXP, o máquina virtual Windows Server 2016, o la edición de Windows Server 2019 Standard o Datacenter.
. Asegúrese de que la máquina virtual está conectada a la red, unida al dominio y accesible a través de RDP.
. Instala el software Edge de almacenamiento en caché perimetral de BlueXP más reciente.
. Identifica el servidor de gestión de almacenamiento en caché perimetral y la instancia de Core de BlueXP.
. Configura la instancia de Edge de almacenamiento en caché perimetral de BlueXP.




== Requisitos de Edge para el almacenamiento en caché en el edge de BlueXP

El edge caching Edge de BlueXP se ha diseñado para funcionar en todas las plataformas que admiten Windows Server 2016 y 2019, aportando LA TECNOLOGÍA simplificada a las oficinas remotas corporativas y más allá. De forma crítica, el almacenamiento en caché perimetral de BlueXP se puede poner en marcha en tu infraestructura de hardware, en la virtualización o en entornos de nube pública o híbrida en casi todos los casos si cumplen ciertos requisitos del nivel básico.

Edge requiere los siguientes recursos de hardware y software para funcionar de manera óptima. Para obtener más información acerca de las directrices de tamaño generales, consulte link:concept-before-you-begin-to-deploy-gfc.html#sizing-guidelines["directrices de tamaño"].



=== Dispositivo servidor reforzado

El paquete de instalación de almacenamiento en caché perimetral de BlueXP crea un dispositivo de software reforzado en cualquier instancia de Microsoft Windows Server. _No desinstalar_ El paquete de almacenamiento en caché perimetral de BlueXP. La desinstalación del almacenamiento en caché perimetral de BlueXP afectará a la funcionalidad de la instancia de servidor y puede requerir una recompilación completa de la instancia del servidor.



=== Requisitos físicos de hardware

* 4 núcleos de CPU como mínimo
* 16 GB de RAM como mínimo
* NIC dedicado único o redundante de 1 Gbps
* SSD o HDD SAS de 10 000 rpm (opción preferida)
* Controladora RAID con la funcionalidad de almacenamiento en caché de escritura simultánea habilitada




=== Requisitos de implementación virtual

Se sabe que las plataformas de hipervisores están sujetas a la degradación del rendimiento desde la perspectiva de un subsistema de almacenamiento (por ejemplo, latencia). Para obtener un rendimiento óptimo mediante el almacenamiento en caché perimetral de BlueXP, se recomienda una instancia de servidor físico con SSD.

Para obtener el mejor rendimiento en entornos virtuales, además de los requisitos físicos del host, se deben cumplir los siguientes requisitos y reservas de recursos:

Microsoft Hyper-V 2012 R2 y posterior:

* Procesador (CPU): Las CPU deben establecerse como *estático*: Mínimo: 4 núcleos vCPU.
* Memoria (RAM): Mínimo: 16 GB establecido como *estático*.
* Aprovisionamiento de discos duros: Los discos duros deben configurarse como *disco fijo*.


VMware vSphere 6.x y posteriores:

* Procesador (CPU): Se debe establecer la reserva de los ciclos de la CPU. Mínimo: 4 núcleos vCPU a 10000 MHz.
* Memoria (RAM): Mínimo: Reserva de 16 GB.
* Provisionamiento de discos duros:
+
** El aprovisionamiento de disco debe definirse como *Thick provisioned eager zeroed*.
** Los recursos compartidos de disco duro deben configurarse en *Alta*.
** Devices.hotplug debe establecerse en *False* mediante vSphere Client para evitar que Microsoft Windows presente unidades de almacenamiento en caché perimetral de BlueXP como extraíbles.


* Conexión en red: La interfaz de red se debe establecer en *VMXNEL3* (puede requerir herramientas de VM).


Edge se ejecuta en Windows Server 2016 y 2019, por lo que la plataforma de virtualización debe admitir el sistema operativo, así como la integración con utilidades que mejoran el rendimiento del sistema operativo invitado de la VM y la gestión de la VM, como VM Tools.



=== Requisitos de tamaño de particiones

* C:\ - mínimo 250 GB (volumen sistema/arranque)
* D:\: Mínimo de 1 TB (volumen de datos independiente para la caché global de archivos inteligente*)


*el tamaño mínimo es el doble del conjunto de datos activo. El volumen de caché (D:\) puede ampliarse y sólo está restringido por las limitaciones del sistema de archivos NTFS de Microsoft Windows.



=== Requisitos del disco de caché inteligente de archivos de Global File Cache

La latencia de disco en el disco de caché de archivos inteligente (D:\) de Global File Cache debería ofrecer una latencia de disco de I/o media de < 0,5 ms y un rendimiento de 1 MB por usuario simultáneo.

Para obtener más información, consulte https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Guía del usuario de caché global de archivos de NetApp"^].



=== Redes

* Firewall: Se deben permitir los puertos TCP entre el almacenamiento en caché perimetral de BlueXP y las instancias de Edge y Management Server y Core.
+
Puertos TCP de almacenamiento en caché perimetral de BlueXP: 443 (HTTPS - LMS), 6618 - 6630.

* Los dispositivos de optimización de redes (como Riverbed Steelhead) deben estar configurados para que pasen a través de los puertos específicos del almacenamiento en caché perimetral de BlueXP (TCP 6618-6630).




=== Estación de trabajo cliente y prácticas recomendadas de la aplicación

El almacenamiento en caché perimetral de BlueXP se integra de manera transparente en los entornos del cliente, lo cual permite a los usuarios acceder a datos centralizados utilizando sus estaciones de trabajo cliente y ejecutando así aplicaciones empresariales. Con el almacenamiento en caché perimetral de BlueXP, se accede a los datos a través de una asignación directa de unidades o a través de un espacio de nombres DFS. Para obtener más información sobre la estructura de almacenamiento en caché perimetral de BlueXP, el almacenamiento en caché de archivos inteligente y los aspectos clave del software, consulte el link:concept-before-you-begin-to-deploy-gfc.html["Antes de empezar a implementar el almacenamiento en caché perimetral de BlueXP"^] sección.

Para garantizar una experiencia y un rendimiento óptimos, es importante cumplir con los requisitos y las prácticas recomendadas del cliente de Microsoft Windows, tal y como se describe en la Guía del usuario de la caché global de archivos. Esto se aplica a todas las versiones de Microsoft Windows.

Para obtener más información, consulte https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Guía del usuario de caché global de archivos de NetApp"^].



=== Mejores prácticas de firewall y antivirus

Mientras que el almacenamiento en caché perimetral de BlueXP hace un esfuerzo razonable para validar que los paquetes de aplicaciones antivirus más comunes son compatibles con Global File Cache, NetApp no puede garantizar ni se responsabiliza de las incompatibilidades o problemas de rendimiento ocasionados por estos programas o las actualizaciones, los Service Packs o las modificaciones asociadas.

NetApp no recomienda la instalación ni la aplicación de supervisión o soluciones antivirus en ninguna instancia habilitada con almacenamiento en caché perimetral de BlueXP (el núcleo o Edge). Si la solución se instalara, por elección o por política, deberán aplicarse las siguientes prácticas recomendadas y recomendaciones. Si desea conocer los paquetes antivirus habituales, consulte el Apéndice A de la https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Guía del usuario de caché global de archivos de NetApp"^].



=== Configuración del firewall

* Firewall de Microsoft:
+
** Conserve la configuración del firewall de forma predeterminada.
** Recomendación: Deje los servicios y la configuración del firewall de Microsoft en la configuración predeterminada de DESACTIVADO y sin iniciar para las instancias estándar de Edge de almacenamiento en caché perimetral de BlueXP.
** Recomendación: Deje LA configuración y los servicios del firewall de Microsoft en LA configuración predeterminada DE ACTIVADO y comience para las instancias de Edge que también ejecuten la función controlador de dominio.


* Firewall de la empresa:
+
** La instancia principal de almacenamiento en caché perimetral de BlueXP escucha en los puertos TCP 6618-6630, lo que garantiza que las instancias de Edge de almacenamiento en caché perimetral de BlueXP se puedan conectar a estos puertos TCP.
** Las instancias de almacenamiento en caché perimetral de BlueXP requieren la comunicación con el servidor de administración de almacenamiento en caché perimetral de BlueXP en el puerto TCP 443 (HTTPS).


* Los dispositivos/soluciones de optimización de red deben estar configurados para que pasen a través de puertos específicos del almacenamiento en caché del perímetro de BlueXP.




=== Mejores prácticas de antivirus

NetApp ha probado productos antivirus más utilizados, como Cylance, McAfee, Symantec, Sophos, Trend Micro y Kaspersky, Crowd Strike, Cisco AMP, Tannium y Windows Defender para su uso en combinación con el almacenamiento en caché perimetral de BlueXP. El software antivirus debe contar con la certificación de NetApp y solo es compatible si se configura con la lista de exclusión adecuada. Consulte el Apéndice A de la https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Guía del usuario de caché global de archivos de NetApp"^]


NOTE: Añadir antivirus a un dispositivo Edge puede tener un efecto del 10-20% sobre el rendimiento del usuario.

Para obtener más información, consulte https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Guía del usuario de caché global de archivos de NetApp"^].



==== Configurar exclusiones

El software antivirus u otras utilidades de indexación o análisis de terceros nunca deben analizar la unidad D:\ en la instancia de Edge. Estos análisis de la unidad de servidor Edge D:\ darán como resultado numerosas solicitudes de apertura de archivos para todo el espacio de nombres de caché. Esto provocará que se optimicen en el centro de datos las búsquedas de archivos en la WAN de todos los servidores de archivos. Se producirán inundaciones en la conexión WAN y cargas innecesarias en la instancia de Edge, lo que provocaría una degradación del rendimiento.

Además de la unidad D:\, por lo general se deberían excluir de todas las aplicaciones antivirus los siguientes directorios y procesos de almacenamiento en caché perimetral de BlueXP:

* `C:\Program Files\TalonFAST\`
* `C:\Program Files\TalonFAST\Bin\LMClientService.exe`
* `C:\Program Files\TalonFAST\Bin\LMServerService.exe`
* `C:\Program Files\TalonFAST\Bin\Optimus.exe`
* `C:\Program Files\TalonFAST\Bin\tafsexport.exe`
* `C:\Program Files\TalonFAST\Bin\tafsutils.exe`
* `C:\Program Files\TalonFAST\Bin\tapp.exe`
* `C:\Program Files\TalonFAST\Bin\TappN.exe`
* `C:\Program Files\TalonFAST\Bin\FTLSummaryGenerator.exe`
* 'C:\Archivos de programa\TalonFAST\Bin\GfcCIAgentService.exe'
* `C:\Program Files\TalonFAST\Bin\RFASTSetupWizard.exe`
* `C:\Program Files\TalonFAST\Bin\TService.exe`
* `C:\Program Files\TalonFAST\Bin\tum.exe`
* `C:\Program Files\TalonFAST\FastDebugLogs\`
* `C:\Windows\System32\drivers\tfast.sys`
* `\\?\TafsMtPt:\` o. `\\?\TafsMtPt*`
* `\Device\TalonCacheFS\`
* `\\?\GLOBALROOT\Device\TalonCacheFS\`
* `\\?\GLOBALROOT\Device\TalonCacheFS\*`




== Política de soporte de NetApp

Las instancias de almacenamiento en caché en el edge de BlueXP están diseñadas específicamente como la aplicación principal que se ejecuta en una plataforma Windows Server 2016 y 2019. El almacenamiento en caché perimetral de BlueXP requiere acceso prioritario a recursos de plataforma, por ejemplo, disco, memoria, interfaces de red y puede exigir mucho estos recursos. Las puestas en marcha virtuales requieren reservas de memoria/CPU y discos de alto rendimiento.

* Para las puestas en marcha de sucursales, los servicios y aplicaciones compatibles que hay en el servidor que ejecuta el almacenamiento en caché perimetral de BlueXP se limitan a:
+
** DNS/DHCP
** Controladora de dominio de Active Directory (el almacenamiento en caché en el perímetro de BlueXP debe estar en un volumen independiente)
** Servicios de impresión
** System Center Configuration Manager (SCCM) de Microsoft
** Agentes del sistema del lado del cliente y aplicaciones antivirus aprobados para el almacenamiento en caché perimetral de BlueXP


* El soporte y mantenimiento de NetApp solo se aplica al almacenamiento en caché perimetral de BlueXP.
* No se admite el software de productividad de la línea de negocio, que suele requerir muchos recursos, por ejemplo, servidores de bases de datos, servidores de correo, etc.
* El cliente es responsable de cualquier software de almacenamiento en caché en el edge que no sea de BlueXP que se pueda instalar en el servidor que ejecuta el almacenamiento en caché en edge de BlueXP:
+
** Si algún paquete de software de terceros provoca conflictos de software o recursos con el rendimiento o el almacenamiento en caché perimetral de BlueXP, es posible que la organización de soporte de NetApp requiera que el cliente deshabilite o elimine el software del servidor que ejecuta el almacenamiento en caché perimetral de BlueXP.
** Es la responsabilidad del cliente de toda la instalación, la integración, el soporte y la actualización de cualquier software añadido al servidor que ejecuta la aplicación de almacenamiento en caché perimetral de BlueXP.


* Las utilidades/agentes de administración de sistemas, como las herramientas antivirus y los agentes de licencia, pueden coexistir. Sin embargo, a excepción de los servicios y aplicaciones compatibles enumerados anteriormente, estas aplicaciones no son compatibles con el almacenamiento en caché perimetral de BlueXP y deben seguirse las mismas directrices anteriores:
+
** Es responsabilidad del cliente por toda la instalación, integración, asistencia y actualización de cualquier software añadido.
** Si un cliente instala un paquete de software de terceros que provoca (o se sospecha que está causando) conflictos de software o recursos con el rendimiento o el almacenamiento en caché perimetral de BlueXP, es posible que la organización de soporte de BlueXP Edge Cache sea un requisito para deshabilitar o quitar el software.



