---
sidebar: sidebar 
permalink: fixed-issues.html 
keywords: fixed issues, release notes, fixes, gfc, global file cache 
summary: Consulta los problemas que se han solucionado en el almacenamiento en caché perimetral de BlueXP. 
---
= Problemas solucionados en el almacenamiento en caché perimetral de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Consulta los problemas que se han solucionado en el almacenamiento en caché perimetral de BlueXP.



== 1 de agosto de 2023 (versión 2,3)

* Se han realizado las siguientes correcciones de la interfaz de usuario de Optimus Configuration:
+
** Muestra información significativa para errores en lugar de cadenas de excepción.
** Muestra la fecha de caducidad de la licencia correctamente en lugar de los valores predeterminados.
** Muestra correctamente los campos de nombre de usuario/contraseña cuando SSL está habilitado en la interfaz de usuario.
** No deja de responder cuando se configura un núcleo GFC inaccesible en la ficha de configuración Optimus UI Edge.
** Permite seleccionar varios nombres de caché/borde en la lista desplegable Borde.


* La información de resumen de licencia se muestra correctamente mientras se visualizan las licencias caducadas y no vencidas.
* Se ha corregido que el servicio TappN se reiniciara sólo cuando la configuración se actualizara correctamente.
* Se ha agregado un botón de actualización en el asistente por primera vez para mostrar el número de aristas.
* La información de SSL ahora se muestra en la página de resumen del asistente por primera vez.
* Se ha añadido infraestructura en Tum para permitir la configuración de tiempos de espera de minivolcado y realizar un minivolcado correctamente.
* Optimus y el asistente por primera vez mostrarán el recuento de licencias apropiado y mostrarán una excepción cuando el recuento de licencias se convierta en cero.
* Optimus PSM ahora muestra un mensaje de error apropiado cuando el nombre del servidor Edge introducido está vacío.
* Se ha solucionado un problema por el que los trabajos de rellenado previo no se aplicaban correctamente a varios nombres de caché en Optimus PSM.
* La configuración del Administrador de licencias se ha mejorado para mostrar errores graves en lugar de errores de software.
* La interfaz de usuario de registro de Zoura mostrará un error si ya está configurada.
* Optimus UI y Optimus PSM ahora muestran los requisitos de CPU y memoria de 8 CPU y 32 GB de RAM respectivamente.




== 27 de marzo de 2023 (versión 2.2)

* Se ha solucionado el problema de convertir el formato de tiempo de ejecución de un trabajo de rellenado previo para la opción de "última modificación de tiempo".
* Se ha solucionado un problema relacionado con el análisis de la transferencia de archivos y su transferencia al servicio Cloud Insights.
* La sincronización de bordes de los archivos en todos los suscriptores se vuelve a conectar automáticamente cuando hay una desconexión con el editor.
* Ejecución fija de trabajos de rellenado previo en un dispositivo Edge si está conectado a varios núcleos.
* Optimus UI ahora muestra la lista Connected Edge en un editor que participa en la funcionalidad de Edge Sync.




== 24 de octubre de 2022 (versión 2.1)

* Durante la configuración de licencias, se realiza una validación adicional del número de suscripción GFC.
* GFC ha añadido soporte para ampliar la licencia durante un período específico para las licencias basadas en Zuora. Póngase en contacto con el soporte GFC.
* Se ha añadido un retardo de 15 segundos antes de escribir un minivolcado después de un bloqueo. También se ha añadido un temporizador para supervisar el minidump y salir del proceso por la fuerza si el volcado no se completa en 60 segundos. Estas mejoras menores ayudarán a un mejor análisis.
* Se ha eliminado la propagación de información de transferencia de archivos individuales a Cloud Insights, pero se ha añadido la propagación de información de resumen de transferencia de archivos a Cloud Insights. De este modo se reduce la enorme carga en CI.
* Incorporación de datos fijos y metadatos en Cloud Insights. Esto permite la visualización de datos CI.
* Se ha corregido la interfaz de usuario de Optimus Configuration para que no se cuelgue mientras se hace clic en el botón "Registrar instancia en CI".
* Se ha solucionado un problema por el que el monitor tService se dejaba manual durante la configuración inicial.
* Se han corregido errores menores en el servicio cliente de GFC CI Agent.




== 25 de julio de 2022 (versión 2.0)

* Optimus se mejora añadiendo límites de límite a los parámetros de fecha/hora para la configuración de adición de trabajos de prepoblación.
* Optimus PSM muestra ahora los detalles correctos de la CPU en los detalles de presolicitud del sistema.
* Se ha corregido una excepción en la interfaz de usuario durante la configuración de sincronización perimetral entre introducir los detalles del coordinador y hacer clic en el botón Actualizar.
* Se ha mejorado la interfaz de usuario de Optimus para activar/desactivar la función Edge Sync en el perímetro.
* Se ha solucionado el problema del intervalo de fechas en el Administrador del servidor de licencias para el agregador de licencias de Zuora.
* Se ha corregido el PSM Optimus para mostrar la información de recuento de arrendamiento.
* Lógica del servidor de administración de licencias fija sobre el actualizador de configuración durante una actualización.




== 23 de junio de 2022 (versión 1.3.1)

* Tras la actualización, la versión correcta de Microsoft redistribuible no se instala correctamente y, como resultado, Tum no se inicia. El instalador GFC se ha solucionado para instalar la versión redistribuible correcta.
* El servicio GFC License Manager (LMS) actualiza ahora la información de configuración, en lugar de sobrescribirla.
* La interfaz de usuario de Configuración ahora se enlaza al System.net.http dll correcto durante el proceso de actualización.




== 19 de mayo de 2022 (versión 1.3.0)

* Se actualiza la página Configuration UI de la funcionalidad Edge Sync.
* Se ha solucionado un problema al agregar trabajos de rellenado previo para varios bordes al mismo tiempo mediante los cmdlets de PowerShell.
* Se ha solucionado un problema de visualización en la interfaz de usuario web de LMS que muestra la suscripción a NetApp.
* La secuencia de comandos de PowerShell para la configuración de LMS utiliza TLS 1.2.
* Se solucionó un problema en TappN (servicio de pre-población) y se le permitió continuar ejecutando el trabajo, a pesar de las disconexiones transitorias o de los reinicios de Tum.
* El servicio de rellenado previo de TappN se actualiza para omitir los archivos de recuperación si el espacio libre en la caché cae por debajo del valor del umbral inferior.
* Se ha solucionado un problema en el servicio de servidor de License Manager (LMS) mientras se escribía un registro de rastreo.
* La infraestructura de registro de Tum se actualiza para ser más escalable con un alto rendimiento.

