---
settings:
  name: Global File Cache
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr
sidebar:
  entries:
  - title: Documentos de Global File Cache
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
    - title: Problemas solucionados
      url: "/fixed-issues.html"
  - title: Manos a la obra
    entries:
    - title: Obtenga más información sobre la caché global de archivos
      url: "/concept-gfc.html"
    - title: Requisitos previos de la caché global de archivos
      url: "/concept-before-you-begin-to-deploy-gfc.html"
    - title: Despliegue y licencia de Global File Cache
      url: "/task-gfc-getting-started.html"
    - title: Requisitos previos de Global File Cache Edge
      url: "/download-gfc-resources.html"
    - title: Ponga en marcha Global File Cache Edge
      url: "/task-deploy-gfc-edge-instances.html"
  - title: Usar caché de archivos global
    entries:
    - title: Formación para el usuario final
      url: "/concept-gfc-enduser-training.html"
    - title: Información adicional
      url: "/reference-gfc-additional-information.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/task-support-registration.html"
    - title: Obtenga ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: Obtenga más información sobre la caché global de archivos
      url: concept-gfc.html
    - title: Novedades
      url: whats-new.html
    - title: Limitaciones
      url: concept-gfc.html#limitations
  - title: Desplegar componentes
    links:
    - title: Ponga en marcha Cloud Volumes ONTAP como plataforma de almacenamiento
      url: task-gfc-getting-started.html#deploy-cloud-volumes-ontap-as-your-storage-platform
    - title: Instale el servidor de gestión global de caché de archivos y el núcleo
        de caché global de archivos
      url: task-gfc-getting-started.html#enable-global-file-cache-in-your-working-environment
    - title: Ponga en marcha instancias globales de File Cache Edge
      url: task-deploy-gfc-edge-instances.html
  - title: Formar a los usuarios
    links:
    - title: Formación para el usuario final
      url: concept-gfc-enduser-training.html
  - title: Blogs y comunidad
    links:
    - title: Comunidad de NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog de BlueXP
      url: https://cloud.netapp.com/blog
    - title: Seminarios web sobre el cloud
      url: https://cloud.netapp.com/events
  - title: Otros recursos
    links:
    - title: Casos de uso de BlueXP
      url: https://cloud.netapp.com/global-file-cache
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Toda la documentación de BlueXP
