---
settings:
  name: BlueXP edge caching
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de almacenamiento en caché perimetral de BlueXP
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
    - title: Problemas solucionados
      url: "/fixed-issues.html"
  - title: Manos a la obra
    entries:
    - title: Obtén más información sobre el almacenamiento en caché del edge de BlueXP
      url: "/concept-gfc.html"
    - title: Requisitos previos para el almacenamiento en caché perimetral de BlueXP
      url: "/concept-before-you-begin-to-deploy-gfc.html"
    - title: Pon en marcha y obtén licencias para el almacenamiento en caché perimetral
        de BlueXP
      url: "/task-gfc-getting-started.html"
    - title: Requisitos previos de BlueXP edge caching Edge
      url: "/download-gfc-resources.html"
    - title: Pon en marcha el almacenamiento en caché en el edge de BlueXP
      url: "/task-deploy-gfc-edge-instances.html"
  - title: Utiliza el almacenamiento en caché de edge de BlueXP
    entries:
    - title: Formación para el usuario final
      url: "/concept-gfc-enduser-training.html"
    - title: Información adicional
      url: "/reference-gfc-additional-information.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/task-support-registration.html"
    - title: Obtenga ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: Obtén más información sobre el almacenamiento en caché del edge de BlueXP
      url: concept-gfc.html
    - title: Novedades
      url: whats-new.html
    - title: Limitaciones
      url: concept-gfc.html#limitations
  - title: Desplegar componentes
    links:
    - title: Ponga en marcha Cloud Volumes ONTAP como plataforma de almacenamiento
      url: task-gfc-getting-started.html#deploy-cloud-volumes-ontap-as-your-storage-platform
    - title: Pon en marcha el servidor de gestión de almacenamiento en caché perimetral
        y el núcleo de BlueXP
      url: task-gfc-getting-started.html#enable-bluexp-edge caching-in-your-working-environment
    - title: Implemente las instancias de Edge en el almacenamiento en caché en el
        edge de BlueXP
      url: task-deploy-gfc-edge-instances.html
  - title: Formar a los usuarios
    links:
    - title: Formación para el usuario final
      url: concept-gfc-enduser-training.html
  - title: Blogs y comunidad
    links:
    - title: Comunidad de NetApp
      url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
    - title: Blog de BlueXP
      url: https://bluexp.netapp.com/blog
    - title: Seminarios web sobre el cloud
      url: https://bluexp.netapp.com/events
  - title: Otros recursos
    links:
    - title: Casos de uso de BlueXP Edge Caching
      url: https://bluexp.netapp.com/global-file-cache
product-family:
  name: BlueXP
  repo: bluexp-family
