---
sidebar: sidebar 
permalink: reference-gfc-additional-information.html 
keywords: global file cache 
summary: Utiliza los siguientes enlaces para obtener más información sobre el almacenamiento en caché en el edge de BlueXP y otros productos de NetApp. 
---
= Información adicional
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utiliza los siguientes enlaces para obtener más información sobre el almacenamiento en caché en el edge de BlueXP y otros productos de NetApp:

* Preguntas frecuentes sobre el almacenamiento en caché en el edge de
+
** Vea una lista de preguntas y respuestas más frecuentes https://bluexp.netapp.com/global-file-cache-faq["aquí"^]


* https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Guía del usuario de caché de archivos global"^]
* Documentación de productos de NetApp
+
** Consulte documentación adicional para los productos cloud de NetApp https://docs.netapp.com/us-en/cloud/["aquí"^]
** Consulte la documentación adicional para todos los productos de NetApp https://www.netapp.com/support-and-training/documentation/["aquí"^]


* El soporte al cliente para los usuarios de caché perimetral de BlueXP con Cloud Volumes ONTAP está disponible a través de los siguientes canales:
+
** Proceso guiado de resolución de problemas, gestión de casos, base de conocimientos, descargas, herramientas y mucho más, vaya https://bluexp.netapp.com/gfc-support["aquí"^]
** Inicie sesión en el soporte de NetApp en https://mysupport.netapp.com[] Con sus credenciales de NSS
** Para obtener asistencia inmediata para un problema P1, llame al +1 856.481.3990 (opción 2)


* El soporte al cliente para los usuarios de almacenamiento en caché en el edge de BlueXP que utilizan Cloud Volumes Services y Azure NetApp Files está disponible a través del soporte estándar de tu proveedor. Póngase en contacto con el Servicio de atención al cliente de Google o con el Servicio de atención al cliente de Microsoft,

